---
on:
  release:
    types:
    - created

jobs:
  target:
    name: release binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - linux
        - windows
        - darwin
        arch:
        - "386"
        - amd64
        - arm64
        exclude:
          -
            arch: "386"
            os: darwin
          -
            arch: arm64
            os: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.26
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.os }}
        goarch: ${{ matrix.arch }}
        goversion: 'https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz'
        project_path: ./
        binary_name: alertmanager-discord
